sudo: required
services:
  - docker

before_install:
  - docker build -t dk081818/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dk081818/react-test npm test -- --coverage

after_success:
  - docker build -t dk081818/multi-client ./client
  - docker build -t dk081818/multi-nginx ./nginx
  - docker build -t dk081818/multi-server ./server
  - docker build -t dk081818/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dk081818/multi-nginx
  - docker push dk081818/multi-server
  - docker push dk081818/multi-worker
  - docker push dk081818/multi-client

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-751441425035
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY